---
- hosts: localhost

  vars_files:
    - vars/packages.yaml

  tasks:
    # Do OS-specific setup
    - ansible.builtin.import_tasks: tasks/pacman.yml
      when: ansible_facts["distribution"] == "Archlinux"
    - ansible.builtin.import_tasks: tasks/brew.yml
      when: ansible_facts["distribution"] == "MacOSX"
    # Finish by linking config files
    - ansible.builtin.import_tasks: tasks/stow.yml
