
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[font.offset]
x = 1
y = 1

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[scrolling]
history = 100000

[window]
dynamic_title = true
option_as_alt = "Both"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]
