# === LSP Configs ===
# Python
[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = [
  { name = "ruff-lsp", only-features = [ "diagnostics" ] },
  { name = "pyright", except-features = [ "format", "diagnostics" ] },
]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

# JS/TS
# TypeScript
[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, { name = "efm", only-features = [ "diagnostics", "format" ] }]

[language-server.efm]
command = "efm-langserver"

[language-server.typescript-language-server]
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

# Markdown
[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

# CSS
[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
language-servers = [ "vscode-css-language-server" ]
indent = { tab-width = 2, unit = "  " }

# Fish
[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

# Groovy
[[language]]
name = "groovy"
file-types = ["groovy", "Jenkinsfile", "jenkinsfile"]

# GDScript
[[language]]
name = "gdscript"
formatter = { command = "gdformat", args = ["-"] }
auto-format = true
