;;; weakfish-core.el --- Core editor defaults -*- lexical-binding: t; -*-

;;; Commentary:
;; Baseline Emacs behavior and settings that other modules build on.

;;; Code:

;; Keep runtime state out of the repo root so batch verification only leaves
;; predictable cache files behind.
(defvar weakfish/cache-directory
  (file-name-as-directory (expand-file-name "cache" user-emacs-directory))
  "Directory for files generated by this Emacs configuration.")

(make-directory weakfish/cache-directory t)

;; Keep machine-generated Custom settings out of this hand-written file.  Emacs
;; writes these when you use customization UIs such as `M-x customize'.
(setq custom-file (locate-user-emacs-file "custom.el"))
(load custom-file 'noerror 'nomessage)

;; Restore normal garbage collection after startup.  16 MB is conservative: low
;; enough to avoid long pauses, high enough to avoid constant collections.
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 16 1024 1024))))

;; A small baseline of modern defaults.  These are built-in Emacs features, not
;; packages, and make the editor feel less surprising for programming.
(setq inhibit-startup-screen t
      ring-bell-function 'ignore
      make-backup-files nil
      auto-save-default nil
      create-lockfiles nil
      delete-by-moving-to-trash t
      use-short-answers t)

;; On macOS, make Command act as Emacs Meta so `M-x' is `Cmd-x'.  Leave Option
;; available for normal macOS character input instead of using it as Meta.
(when (eq system-type 'darwin)
  (setq mac-command-modifier 'meta
        ns-command-modifier 'meta
        mac-option-modifier nil
        ns-option-modifier nil
        mac-right-option-modifier nil
        ns-right-option-modifier nil))

;; Iosevka Nerd Font keeps Iosevka's compact programming shape while including
;; the icon glyphs that many Emacs UI packages can use later.
(defvar weakfish/font-family "Iosevka Nerd Font"
  "Default monospace font family.")

(defvar weakfish/font-height 140
  "Default font height in tenths of a point.")

(add-to-list 'default-frame-alist
             `(font . ,(format "%s-%d" weakfish/font-family (/ weakfish/font-height 10))))

(when (display-graphic-p)
  (set-face-attribute 'default nil
                      :family weakfish/font-family
                      :height weakfish/font-height))

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Relative line numbers make Vim-style movement easier: commands like `5j' or
;; `12k' match the numbers shown beside each line.  The current line still shows
;; its absolute number so error messages and compiler output remain easy to map.
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
(column-number-mode 1)
(delete-selection-mode 1)
(electric-pair-mode 1)
(global-auto-revert-mode 1)
(global-hl-line-mode 1)

(setq scroll-conservatively 101
      scroll-margin 3
      scroll-step 1
      pixel-scroll-precision-use-momentum nil)

(when (fboundp 'pixel-scroll-precision-mode)
  (pixel-scroll-precision-mode 1))

(provide 'weakfish-core)
;;; weakfish-core.el ends here
