# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Move the directory to the second line
# extra space to pad start
format = """
 $directory\ 
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$character\
"""

[character] # The name of the module we are configuring is 'character'
success_symbol = '[󰘧](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
